language: ruby
sudo: false
gemfile: nubis/travis/Gemfile
cache:
  bundler: true
  directories:
  - "${HOME}/bin"
  - nubis/librarian-puppet
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck
script:
- nubis/travis/run-checks
notifications:
  slack:
    secure: rYpdsbkeEBMWLM2L6z6djtALeJg1r3gnSw9sHqM/vQuJu+CAgzrbx809M5M8HxcP/mT+uf7pqrqZwanC+vrrqPUzPKLeWqcq3lagQY/Iuul2ByAnFG8SjmRXh6bV2pDSNcmBrhS6Br33mqYhnynsabyM418uBMJltSGqJm9N8MZhvY7+CMOyx81mcS25w4C1FtlRVUUMojK96tp7NLFBwpTlXJkDvc0O0T+zt9nTl/ckKpNx/1mWaRpk1SH3SRW6Afm3b708cv5JFogl3G/Mhy60UAdn176HCed8MwkIhb9rLV8UWk0NcMGzuXl9v74wPKM2sjc+6lzkVi9t8Hhrj6H6RJarNUBaMwmh0plH5FZq+KduOSB64sRBrFuZes5QQYLbNDJ/IbGVdLO4x9yX5GQBITR0itB7qB2FIYnFmpQQWN/DNDWGr4XA7h26fS6fzu5Aet3rxOn8Nkq+rTSDgjtC+Hd7I5T/Xl0Zjt1sLom93ZSt+WsEQ0+qf8Dfhki4INrDFTFy40ny3m6t18rGsbvmZzp4CloZXSk47O3JoLTCforWJNSGXndW6SSVrxliY+zNGXzIy5cyOBPuAdLmNEGNm2OlG73pEy4VqcZpXoHtWmWWMEEY6Sep3GCjcyzYxA5gWXbqpRTqH28p+gPRrV9hsH39NI5usJNNqObF/Wk=
